services:
  # 1. NOTRE BASE DE DONNÉES (déjà en place)
  db_dev:
    image: mysql:8.0
    container_name: vide_grenier_db_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vide_grenier
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    ports:
      - "3306:3306"
    volumes:
      - ./sql/import.sql:/docker-entrypoint-initdb.d/import.sql

  # 2. NOTRE MOTEUR PHP
  php_dev:
    build: . # Le "." dit à Docker de chercher le "Dockerfile" dans le dossier actuel
    container_name: vide_grenier_php_dev
    volumes:
      # On synchronise ton dossier actuel (.) avec le dossier du serveur (/var/www/html). 
      # Si tu modifies un fichier sur ton PC, ça le modifiera en direct dans le conteneur !
      - .:/var/www/html 

  # 3. NOTRE SERVEUR WEB (NGINX)
  web_dev:
    image: nginx:latest
    container_name: vide_grenier_web_dev
    ports:
      # On mappe le port 8080 de ton PC sur le port 80 du conteneur.
      - "8080:80" 
    volumes:
      - .:/var/www/html # Nginx a aussi besoin de voir tes fichiers
      - ./nginx-configuration.txt:/etc/nginx/conf.d/default.conf # On injecte la config du code legacy
    depends_on:
      - php_dev # On demande à Nginx d'attendre que PHP soit prêt
      - db_dev